### ISSUE TITLE
詞彙方言差 序號384 與辭典有出入

### ISSUE THREAD

**Issue by glll4678** [g0v/moedict-data-twblg#15]
384,[方1]0385,生鐵,生　sinn,生　sinn,"生　sinn, 鑄生仔　tsù-sinn-á",生仔　senn-á,生仔　senn-á,生仔　senn-á,鍟　sinn,鍟　sinn,鍟　sinn,鍟仔　senn-á

http://twblg.dict.edu.tw/holodict_new/index/cuankho.jsp?no=0385

鍟

**Comment by sih4sing5hong5** [comment]
ai3 khi3 kau3-iok8-poo7 phue1-siunn1 huan2-ing3, in1 to7 e7 kai2
au7-pai2 e5 tsu1-liau7 tsiah4 e7 si7 tioh8--e5
http://twblg.dict.edu.tw/holodict_new/index.html

**Comment by sih4sing5hong5** [comment]
@glll4678 你bue2--a2 kam2 u7 kia3 phue1 ?

**Comment by glll4678** [comment]
Tú kià--ah.

**Comment by sih4sing5hong5** [comment]
https://github.com/g0v/moedict-data-twblg/pull/19/files#diff-32069560477f1781848b4e8ff3c03d03L373 有更新--ah
