### ISSUE TITLE
"㧌" 的第二個例句跑到釋義裡了

### ISSUE THREAD

**Issue by jianiau** [g0v/moedict-data-twblg#16]
釋義.csv

釋義總序號 | 主編碼 | 釋義順序 | 詞性代號 | 釋義
-- | -- | -- | -- | --
18101 | 13588 | 1 | 9 | 揍、打。以拳頭或棍棒用力地打下去。
18102 | 13588 | 2 | 3 | 凹陷。伊的車門予人挵一㧌。I ê tsia-mn̂g hōo lâng lòng tsi̍t mau. (他的車門被撞了個凹陷。)

**Comment by sih4sing5hong5** [comment]
可以先回報[教育部](https://email.moe.gov.tw/EDU_WEB/sendmail/send.php?sGo=1)
然後再[申請新的資料](http://twblg.dict.edu.tw/holodict_new/compile1_6_1.jsp)下來
再pr更新專案資料

**Comment by jianiau** [comment]
請問教育部給的 raw data 的就是 *.csv 嗎，
回報時是不是直接說明哪個檔案錯誤就可以了？

**Comment by sih4sing5hong5** [comment]
原始是xls，不過issue這樣教育部應該看有XD

jianiau <notifications@github.com> 於 2018年7月9日週一 上午9:53 寫道：

**Comment by sih4sing5hong5** [comment]
#19 有更新--ah
例句有ka--ah

https://github.com/g0v/moedict-data-twblg/pull/19/files#diff-a166070adf23fbc6e129968724e5bcfdR14040
