### ISSUE TITLE
釋義.csv 有一大塊資料缺失

### ISSUE THREAD

**Issue by ekliao** [g0v/moedict-data-twblg#37]
例如第20006條主詞目，是「三」字（文言發音sam），但在釋義.csv檔案裡找不到釋義（raw, pua, uni版都一樣），線上版有如下釋義：

>> 數字。例：三生有幸　sam-sing-iú-hīng。

實際上，發現從第20001條開始有大約8000條詞目在釋義.csv中不見釋義，全部空白。

方便的話，希望可以補回來，謝謝！

**Comment by sih4sing5hong5** [comment]
Ē-tàng申請新資料 https://twblg.dict.edu.tw/holodict_new/compile1_6_1.jsp

網站ê編號是看 `n_no` 參數

### 170
![2019-12-03 07-00-06 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/70002355-bf7cde80-159a-11ea-8c07-2ce5995ad051.png)

### 20006
![2019-12-03 07-00-17 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/70002366-c572bf80-159a-11ea-9de7-4955a597232a.png)

**Comment by ekliao** [comment]
啊，原來釋義可在#170找到，而#20000起那一大塊屬於「單字不成詞者」屬性，沒有定義。謝謝你指出，我之前沒注意找。這樣的話，就沒有缺失了，可以把這issue了結起來。
